apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node-wireguard
  namespace: auth
spec:
  serviceName: "node-wireguard"
  replicas: 2
  selector:
    matchLabels:
      app: node-wireguard
  template:
    metadata:
      labels:
        app: node-wireguard
    spec:
      serviceAccountName: jenkins
      initContainers:
        - name: wireguard-setup
          image: ubuntu:latest
          command:
            - /bin/bash
            - -c
            - |
              # Install necessary packages
              apt-get update && apt-get install -y \
                wireguard \
                wireguard-tools \
                iproute2 \
                iptables \
                iputils-ping \
                curl \
                && apt-get clean && rm -rf /var/lib/apt/lists/*

              # Generate WireGuard keys
              PRIVATE_KEY=$(wg genkey)
              PUBLIC_KEY=$(echo "$PRIVATE_KEY" | wg pubkey)

              # Pod-specific variables
              POD_NAME=$(hostname)
              POD_INDEX=$(echo "$POD_NAME" | grep -oE '[0-9]+$')
              LISTEN_PORT=$((51820 + POD_INDEX))
              PEER_IP="10.8.0.$((1 + POD_INDEX))"

              # Save keys for later use
              mkdir -p /etc/wireguard
              echo "$PRIVATE_KEY" > /etc/wireguard/privatekey
              echo "$PUBLIC_KEY" > /etc/wireguard/publickey
              echo "$LISTEN_PORT" > /etc/wireguard/listenport

              # Configure WireGuard interface
              cat <<EOF > /etc/wireguard/wg0.conf
              [Interface]
              PrivateKey=$PRIVATE_KEY
              Address=$PEER_IP/24
              ListenPort=$LISTEN_PORT
              SaveConfig=true
              EOF

              # Enable IP forwarding and NAT rules
              echo "1" > /proc/sys/net/ipv4/ip_forward
              sysctl -p || true
              iptables -A FORWARD -i wg0 -j ACCEPT
              iptables -A FORWARD -o wg0 -j ACCEPT
              iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
              iptables -t nat -A POSTROUTING -o wg0 -j MASQUERADE

              # Bring up the WireGuard interface
              wg-quick up wg0 || echo "WireGuard setup failed."

              # Dynamically save configuration
              wg-quick save wg0 || echo "Failed to save WireGuard configuration."
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
      containers:
        - name: node-wireguard
          image: bhargavram458/node-wireguard:latest
          ports:
            - containerPort: 4000
              protocol: TCP
            - containerPort: 51820
              protocol: UDP
            - containerPort: 51821
              protocol: UDP
          env:
            - name: NODE_ENV
              value: production
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: wireguard-config
              mountPath: /etc/wireguard
      volumes:
        - name: wireguard-config
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: node-wireguard
  namespace: auth
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  selector:
    app: node-wireguard
  ports:
    - name: tcp-traffic
      protocol: TCP
      port: 4000
      targetPort: 4000
    - name: udp-traffic-51820
      protocol: UDP
      port: 51820
      targetPort: 51820
    - name: udp-traffic-51821
      protocol: UDP
      port: 51821
      targetPort: 51821
