apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: node-wireguard-hpa
  namespace: wireguard
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: node-wireguard    # The name of your StatefulSet
  minReplicas: 1            # Minimum number of replicas
  maxReplicas: 5            # Maximum number of replicas
  metrics:
    - type: Resource
      resource:
        name: cpu           # Metric to monitor (CPU in this case)
        target:
          type: Utilization
          averageUtilization: 50  # Target CPU utilization (50%)
